### ISSUE TITLE
Rance 4 2.05 map movement lag, stack errors

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/vscode-system3x#1]
I'm running Rance 4 2.05 via VSCode and the extension for debugging. When attempting to move around the map in Rance 4 2.05, it takes multiple clicks or keyboard presses for the game to register any input, a problem that doesn't exist outside the extension. There are no warnings or errors on the console while this is happening.

When the input finally goes through, the debug console gives the warning "*WARNING*(sl_retFar): Stack buffer is illegal" on certain %0: statements (depending on what you were doing at the time). Other than the delay, the code continues to operate correctly.

The error doesn't seem to happen anywhere but the map screen, but because it slows map movement so much, I haven't been using the debugger unless I have to so I can't be certain.

**Comment by RottenBlock** [comment]
I've given this some additional testing and it seems I was wrong about the lag, that's something I introduced even though I thought this code was untouched. I'm going to try to find out why, but you don't need to worry about that.

The stack buffer warnings are legitimate, however.

**Comment by kichikuou** [comment]
As for the lag, it sounds like the [game-specific hack](https://github.com/kichikuou/xsystem35-sdl2/commit/e8357c4e6f54e524c7323c5a95400341ccb53349) is not working. The latest build enables the hack [based on the game title](https://github.com/kichikuou/xsystem35-sdl2/commit/c4dc799c9431ac5583a010948e3a2b2d5bd16e2f), so if you change the argument of the `MT` command, it stops working. (I'm planning to introduce something like system3-sdl2's `game_id` that can be overridden by a command line flag or the `.xsys35rc` file.)


As for the warning, it is harmless. That warning is reported when returning from a label call with `%0`, instead of `\0`. For example:

```
    ~Func:      ; function call

**Func:
    'foo'R
    \LocalFunc: ; label call
    'baz'R
    %0:

*LocalFunc:
    'bar'R
    %0:         ; This returns from Func, so 'baz' will not be displayed!

```

xsystem35 warns because it may be a potential bug, but the behavior (in the above example, returns from `Func`) is the same as the original system39.exe.

**Comment by RottenBlock** [comment]
Oh, I forgot to say thank you for explaining this! And since the lag is solved in the other thread, we can close this.
